sudo: required
services:
  - docker

before_install:
  - docker build -t sredahan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sredahan/react-test npm test -- --coverage

after_success:
  - docker build -t sredahan/multi-client ./client
  - docker build -t sredahan/multi-nginx ./nginx
  - docker build -t sredahan/multi-server ./server
  - docker build -t sredahan/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sredahan/multi-client
  - docker push sredahan/multi-nginx
  - docker push sredahan/multi-server
  - docker push sredahan/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: us-east-2
#   app: multi-docker
#   env: MultiDocker-env
#   bucket_name: elasticbeanstalk-us-east-2-534428062849
#   bucket_path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: 
#     secure: $AWS_SECRET_KEY